---
stages:
  - build
  - test
  - tag
  - deploy

include:
  - project: 'connylegal/mietright_deployments'
    file: '/.gitlab-ci/build-container.yaml'
    ref: main

  - project: 'connylegal/mietright_deployments'
    ref: main
    file: '/.gitlab-ci/deploy.yaml'

variables:
  FAILFASTCI_NAMESPACE: connylegal
  OCI_REPO: img.conny.dev
  CONTAINER: conny/gmail2s3
  IMAGE_NAME: $OCI_REPO/$CONTAINER
  APPNAME: gmail2s3
  APP: gmail2s3
  DEFAULT_TAG: v.$CI_COMMIT_REF_SLUG
  GMAIL2S3_CONF_FILE: tests/data/test_config.yaml

# BUILD IMAGE
build image:
  extends: .build-container
  variables:
    TAG: v.$CI_COMMIT_REF_SLUG

# RUN TEST
unit test:
  image:
    name: img.conny.dev/connylabs/gmail2s3:ci.v1
  stage: build
  script:
    - pytest --cov=$APP --cov-report=html --cov-report=term-missing  --verbose tests --junitxml=report.xml
    - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml
  tags:
    - kubernetes


code lint:
  image:
    name: img.conny.dev/connylabs/gmail2s3:ci.v1
  stage: build
  script:
    - make check
  tags:
    - kubernetes


test image:
  image:
    name: $IMAGE_NAME:v.$CI_COMMIT_REF_SLUG
  needs:
    - "build image"
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - cd /app
    - make test
  tags:
    - kubernetes


# TAGS IMAGES
image tag:
  extends: .tag-main
  needs:
    - "test image"
  variables:
    SOURCE_TAG: v.$CI_COMMIT_REF_SLUG

# Deploy
deploy-staging:
  needs:
    - image tag
  extends: .deploy-staging

deploy-production:
  needs:
    - image tag
  extends: .deploy-production
  stage: deploy
